### ISSUE TITLE
Drush site:install fails without error

### ISSUE THREAD

**Issue by hacor** [bitnami/bitnami-docker-drupal#106]
**Description**

I'm using KubeApps to install Bitname Drupal on my bare metal Kubernetes cluster and just fails without any logs on the `drush site:install` command, even with the `TRACE` environment enabled

**Steps to reproduce the issue:**
Just running Drupal deployment from the KubeApps UI.

**Describe the results you received:**

The contents of my configuration
```
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry and imagePullSecrets
##
# global:
#   imageRegistry: myRegistryName
#   imagePullSecrets:
#     - myRegistryKeySecretName

## Bitnami Drupal image version
## ref: https://hub.docker.com/r/bitnami/drupal/tags/
##
image:
  registry: docker.io
  repository: bitnami/drupal
  tag: 8.7.3-debian-9-r0
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: IfNotPresent
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## Installation Profile
## ref: https://github.com/bitnami/bitnami-docker-drupal#configuration
##
drupalProfile: standard

## User of the application
## ref: https://github.com/bitnami/bitnami-docker-drupal#configuration
##
drupalUsername: hacor

## Application password
## Defaults to a random 10-character alphanumeric string if not set
## ref: https://github.com/bitnami/bitnami-docker-drupal#configuration
##
drupalPassword: SomePassword

## Admin email
## ref: https://github.com/bitnami/bitnami-docker-drupal#configuration
##
drupalEmail: hacornelis@gmail.com

## Set to `yes` to allow the container to be started with blank passwords
## ref: https://github.com/bitnami/bitnami-docker-drupal#environment-variables
allowEmptyPassword: "yes"

##
## External database configuration
##
externalDatabase:
  ## Database host
  # host:

  ## Database user
  # user: bn_drupal

  ## Database password
  # password:

  ## Database name
  # database: bitnami_drupal

##
## MariaDB chart configuration
##
## https://github.com/helm/charts/blob/master/stable/mariadb/values.yaml
##
mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Disable MariaDB replication
  replication:
    enabled: false

  ## Create a database and a database user
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#creating-a-database-user-on-first-run
  ##
  db:
    name: bitnami_drupal
    user: bn_drupal
    ## If the password is not specified, mariadb will generates a random password
    ##
    # password:

  ## MariaDB admin password
  ## ref: https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  # rootUser:
  #   password:

  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  master:
    persistence:
      enabled: true
      ## mariadb data Persistent Volume Storage Class
      ## If defined, storageClassName: <storageClass>
      ## If set to "-", storageClassName: "", which disables dynamic provisioning
      ## If undefined (the default) or set to null, no storageClassName spec is
      ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
      ##   GKE, AWS & OpenStack)
      ##
      # storageClass: "-"
      accessMode: ReadWriteOnce
      size: 8Gi

## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer
## Use ClusterIP if your setup includes ingress controller
##
service:
  type: ClusterIP
  # HTTP Port
  port: 80
  # HTTPS Port
  httpsPort: 443
  ##
  ## nodePorts:
  ##   http: <to set explicitly, choose port between 30000-32767>
  ##   https: <to set explicitly, choose port between 30000-32767>
  #nodePorts:
  #  http: ""
  #  https: ""
  ## Enable client source IP preservation
  ## ref http://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  ##
  externalTrafficPolicy: Cluster

## Configure the ingress resource that allows you to access the
## Drupal installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:
  ## Set to true to enable ingress record generation
  enabled: true

  ## The list of hostnames to be covered with this ingress record.
  ## Most likely this will be just one host, but in the event more hosts are needed, this is an array
  hosts:
  - name: drupal.appsynth.io

    ## Set this to true in order to enable TLS on the ingress record
    ## A side effect of this will be that the backend drupal service will be connected at port 443
    tls: true

    ## Set this to true in order to add the corresponding annotations for cert-manager
    certManager: true

    ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
    tlsSecret: drupal.appsynth-tls

    ## Ingress annotations done as key:value pairs
    ## For a full list of possible ingress annotations, please see
    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
    ##
    ## If certManager is set to true, annotation kubernetes.io/tls-acme: "true" will automatically be set
    annotations:
     kubernetes.io/ingress.class: tectonic

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  drupal:
    ## drupal data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 8Gi

    ## A manually managed Persistent Volume Claim
    ## Requires persistence.enabled: true
    ## If defined, PVC must be created manually before volume will be bound
    ##
    # existingClaim:

    ## If defined, the drupal-data volume will mount to the specified hostPath.
    ## Requires persistence.enabled: true
    ## Requires persistence.existingClaim: nil|false
    ## Default: nil.
    ##
    # hostPath:

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    memory: 2048Mi
    cpu: 1000m

## Configure volume mounts. This is useful for images whose data mount paths are
## different than the default.
##
volumeMounts:
  drupal:
    mountPath: /bitnami/drupal

## Pass extra environment variables to the Drupal container.
##
# extraVars:
# - name: EXTRA_VAR_1
#   value: extra-var-value-1
# - name: EXTRA_VAR_2
#   value: extra-var-value-2

## Configure liveness and readiness probes.
## Drupal core exposes /user/login to unauthenticated requests, making it a good
## default liveness and readiness path. However, that may not always be the
## case. For example, if the image value is overridden to an image containing a
## module that alters that route, or an image that does not auto-install Drupal.
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
#
livenessProbe:
  httpGet:
    path: /user/login
    port: http
  initialDelaySeconds: 120
readinessProbe:
  httpGet:
    path: /user/login
    port: http
  initialDelaySeconds: 30

## Pod annotations
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}
## Prometheus Exporter / Metrics
##
metrics:
  enabled: false
  image:
    registry: docker.io
    repository: lusotycoon/apache-exporter
    tag: v0.5.0
    pullPolicy: IfNotPresent
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    # pullSecrets:
    #   - myRegistryKeySecretName
     ## Metrics exporter pod Annotation and Labels
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9117"
  ## Metrics exporter resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  # resources: {}

```

See the logs returned by the container:
```
Welcome to the Bitnami drupal container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-drupal
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-drupal/issues

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
nami    INFO  Initializing apache
nami    INFO  apache successfully initialized
nami    INFO  Initializing php
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/tmp"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/tmp
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/logs"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/logs
php     TRACE [configurePermissions] List of files: ["/opt/bitnami/php/var","/opt/bitnami/php/var/log","/opt/bitnami/php/var/run"]
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/log
php     TRACE [configurePermissions] File to chown: /opt/bitnami/php/var/run
nami    INFO  php successfully initialized
nami    INFO  Initializing mysql-client
nami    INFO  mysql-client successfully initialized
nami    INFO  Initializing drupal
drupal  DEBUG Creating the Apache configuration vhost file
drupal  DEBUG Creating the Apache configuration https vhost file
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at harsh-afterthought-mariadb:3306
mysql-c TRACE [canConnect] Testing connection with 'bn_drupal' user
mysql-c TRACE [showDatabases] Getting databases for 'bn_drupal' user
mysql-c TRACE [execute] Executing: mysql -N -P 3306 -hharsh-afterthought-mariadb -ubn_drupal -prhfImnioN8 -e SHOW DATABASES;
mysql-c TRACE [execute] Result: {"code":0,"stdout":"bitnami_drupal\ninformation_schema\ntest\n","stderr":""}
mysql-c TRACE [showDatabases] Databases: bitnami_drupal
information_schema
test

mysql-c TRACE [canConnect] Connection with 'bn_drupal' user is successful
mysql-c INFO  MySQL server listening and working at harsh-afterthought-mariadb:3306
drupal  DEBUG Preparing Drupal environment...
drupal  INFO  Installing Drupal with drush...
drupal  TRACE [runProgram] Executing: /opt/bitnami/drupal/vendor/bin/drush site:install standard --db-url=mysql://bn_drupal:rhfImnioN8@harsh-afterthought-mariadb:3306/bitnami_drupal --account-name=hacor --account-mail=hacornelis@gmail.com --account-pass=SomePassword --site-name='My blog' --site-mail=hacornelis@gmail.com -y
```

**Describe the results you expected:**

A working Drupal installation :-)

**Additional information you deem important (e.g. issue happens only occasionally):**

Wordpress works perfectly using the same parameters, so I'm sure Ingress and service configurations are correct

**Version**
- Output of `kubectl version`:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Output of `kubectl get node worker1 -o jsonpath="{.status.nodeInfo.containerRuntimeVersion}"`:

```
docker://18.9.2
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
It's a Bare Metal kubernetes cluster using the `kubeadam` setup

Any suggestions would be appreciated

Thanks!

Hacor

**Comment by alemorcuq** [comment]
Hi, @hacor.

I'm not able to reproduce your issue. I have deployed a Drupal installation using Kubeapps with a configuration similar to yours. 

Does it show any error after failing? What is the output of `kubectl describe pod your-drupal-pod`?

Regards,
Alejandro

**Comment by hacor** [comment]
Hello @alemorcuq 

Here is the output: 
```
Name:               loud-alley-drupal-77bd9fcfb8-b9lt6
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               worker2/10.1.3.22
Start Time:         Fri, 07 Jun 2019 11:55:31 +0200
Labels:             app=loud-alley-drupal
                    chart=drupal-3.3.2
                    pod-template-hash=77bd9fcfb8
                    release=loud-alley
Annotations:        cni.projectcalico.org/podIP: 10.2.5.213/32
Status:             Running
IP:                 10.2.5.213
Controlled By:      ReplicaSet/loud-alley-drupal-77bd9fcfb8
Containers:
  drupal:
    Container ID:   docker://b7351b182fa9e417c65bbcccd497132a8307691412f28d6fcff29a93bcced503
    Image:          docker.io/bitnami/drupal:8.7.3-debian-9-r0
    Image ID:       docker-pullable://bitnami/drupal@sha256:222e566826842f0dd69f5b073b5dfbe9a7450bd717d255aaa6170926e52ab23b
    Ports:          80/TCP, 443/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Sat, 08 Jun 2019 13:57:03 +0200
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Sat, 08 Jun 2019 13:48:59 +0200
      Finished:     Sat, 08 Jun 2019 13:51:58 +0200
    Ready:          False
    Restart Count:  292
    Requests:
      cpu:      1
      memory:   2Gi
    Liveness:   http-get http://:http/user/login delay=120s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/user/login delay=30s timeout=1s period=10s #success=1 #failure=3
    Environment:
      ALLOW_EMPTY_PASSWORD:      yes
      MARIADB_HOST:              loud-alley-mariadb
      MARIADB_PORT_NUMBER:       3306
      DRUPAL_DATABASE_NAME:      bitnami_drupal
      DRUPAL_DATABASE_USER:      bn_drupal
      DRUPAL_DATABASE_PASSWORD:  <set to the key 'mariadb-password' in secret 'loud-alley-mariadb'>  Optional: false
      DRUPAL_PROFILE:            standard
      DRUPAL_USERNAME:           hacor
      DRUPAL_PASSWORD:           <set to the key 'drupal-password' in secret 'loud-alley-drupal'>  Optional: false
      DRUPAL_EMAIL:              hacornelis@gmail.com
    Mounts:
      /bitnami/drupal from drupal-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jhqh4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  drupal-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  loud-alley-drupal-drupal
    ReadOnly:   false
  default-token-jhqh4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jhqh4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From              Message
  ----     ------     ----                   ----              -------
  Warning  Unhealthy  8m7s (x4320 over 26h)  kubelet, worker2  Readiness probe failed: Get http://10.2.5.213:80/user/login: dial tcp 10.2.5.213:80: connect: connection refused
  Warning  BackOff    3m7s (x3404 over 25h)  kubelet, worker2  Back-off restarting failed container
```

I see 2 possible causes here:
- Could it be that the readiness probe causes the pod to shutdown before the installation has finished?
- Could it be that the pod needs more CPU/RAM in order to install drupal (I know PHP scripts sometimes use a lot of CPU and RAM) and I gave him 1 CPU and 2Gb of RAM.

Thanks!

**Comment by alemorcuq** [comment]
Hi, @hacor.

> Could it be that the readiness probe causes the pod to shutdown before the installation has finished?

It's possible. Can you try making the `initialDelaySeconds` of the probes very big and see what happens? It's very weird that the `drush site:install` command fails without any output, so something may be killing it before being able to finish.

> Could it be that the pod needs more CPU/RAM in order to install drupal (I know PHP scripts sometimes use a lot of CPU and RAM) and I gave him 1 CPU and 2Gb of RAM.

I don't think this is the problem here as it works for me with our default configuration:

```
resources:
  requests:
    memory: 512Mi
    cpu: 300m
```
