### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by magick93** [bitnami/bitnami-docker-drupal#112]
**Description**

I'm using the docker-compose file, with added env vars, to set the user and password.

But I still cannot login.

**Steps to reproduce the issue:**

Using the following compose file:

```
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - 'mariadb_data:/bitnami'
  drupal:
    image: 'bitnami/drupal:8'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_PASSWORD=password
      - DRUPAL_USERNAME=user
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      - ALLOW_EMPTY_PASSWORD=yes
      - COMPOSER_MEMORY_LIMIT=-1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'drupal_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local

```

1. Using above file
2. run `docker-compose up`
3. go to localhost and try to login with user/password

**Describe the results you received:**

Cant login

**Describe the results you expected:**

To be able to login
