### ISSUE TITLE
How can I increase the PHP_MEMORY_LIMIT and PHP_MAX_EXECUTION_TIME?

### ISSUE THREAD

**Issue by maggie-drupal** [bitnami/bitnami-docker-drupal#119]
Our deployment yml was updated to contain the bitnami drupal image PHP env variables but the changes aren't applied on the pod. When visiting admin/reports/status/php I see that the values are the default ones and not the ones set in the deployment yaml
```yaml
 env:
            {{- if .Values.memoryLimit }}
            - name: PHP_MEMORY_LIMIT
              value: {{ .Values.memoryLimit | quote }}
            {{- end }}
            {{- if .Values.maxExecutionTime }}
            - name: PHP_MAX_EXECUTION_TIME
              value: {{ .Values.maxExecutionTime | quote }}
            {{- end }}
```

Also I see that in Drupal admin/reports/status/php it says:
Loaded Configuration File | /opt/bitnami/php/lib/php.ini
but in the bitnami image I see that the php.ini is set here: /opt/bitnami/php/etc/php.ini
Could this be the issue?

**Comment by rafariossaa** [comment]
Hi,
  `/opt/bitnami/php/lib/php.ini` is a symbolic link to ` /opt/bitnami/php/etc/php.ini`.
  Could you send the log ? there should be a message indicating that the parameter has been set.

**Comment by maggie-drupal** [comment]
Here are the logs:
[Bitnami Drupal setup actions
Bitnami apache setup
apache 08:47:14.92 DEBUG ==> Validating settings in APACHE_* environment variables
Bitnami PHP setup
php 08:47:14.97 INFO  ==> Configuring PHP options
**php 08:47:14.98 INFO  ==> Setting PHP max_execution_time option
php 08:47:15.01 INFO  ==> Setting PHP memory_limit option**
php 08:47:15.04 INFO  ==> Setting PHP expose_php option
Bitnami MYSQL setup
mysql 08:47:15.10 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
Bitnami DRUPAL setup
drupal 08:47:15.15 DEBUG ==> Validating settings in DRUPAL_* environment variables...
drupal 08:47:15.29 INFO  ==> Restoring persisted Drupal installation
drupal 08:47:15.33 INFO  ==> Trying to connect to the database server
drupal 08:47:15.34 DEBUG ==> Getting host from Drupal database configuration
drupal 08:47:15.36 DEBUG ==> Getting port from Drupal database configuration
drupal 08:47:15.38 DEBUG ==> Getting database from Drupal database configuration
drupal 08:47:15.41 DEBUG ==> Getting username from Drupal database configuration
drupal 08:47:15.43 DEBUG ==> Getting password from Drupal database configuration](url)

However when I visit my drupal site in the /admin/reports/status/php I see the default values and not the ones set in the env variable

**Comment by marcosbc** [comment]
Hi @maggie-drupal, unfortunately I could not reproduce your issue. Here is my docker-compose:

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.5-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  drupal:
    image: 'docker.io/bitnami/drupal:9-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      - PHP_MEMORY_LIMIT=769M
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'drupal_data:/bitnami/drupal'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  drupal_data:
    driver: local
```

And here is the results of PHP's configuration in `/admin/reports/status/php`:

![Screen Shot 2020-12-07 at 15 23 20](https://user-images.githubusercontent.com/5102866/101362260-2b75df00-38a0-11eb-8635-6972576354ea.png)

You can see that the proper value of 769M is set in the configuration for `memory_limit`. Let us know if we're missing anything.
