### ISSUE TITLE
Access denied error when mounting NFS export 

### ISSUE THREAD

**Issue by Abhi-Codes** [bitnami/bitnami-docker-drupal#120]
I am trying to deploy a Drupal pod on Kubernetes cluster with an on-premises MySQL database server . As per the documentation , if we need to persist the application data , we need to have a volume attached . Hence , I have attached a NFS export to the Drupal pod . Below are the yamls  .

```
apiVersion: v1
data:
  DRUPAL_DATABASE_HOST: "wellns-poc-mysql1.infra-dev.company.com"
  DRUPAL_DATABASE_PORT_NUMBER: "3306"
  DRUPAL_DATABASE_NAME: "drupal_tkg"
  DRUPAL_DATABASE_USER: "drupalpoc"
  DRUPAL_DATABASE_PASSWORD: "Dr"
kind: ConfigMap
metadata:
  name: drupal-config
```
---
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  selector:
    matchLabels:
      app: drupal
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal
        tier: frontend
    spec:
      containers:
        - image: quay.io/bitnami/drupal:8.9.11-debian-10-r2
          name: drupal
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 2G
            requests:
              cpu: 1000m
              memory: 1G
          envFrom:
            -
              configMapRef:
                name: drupal-config
          volumeMounts:
            - name: nfs-volume
              mountPath: /bitnami/drupal
      volumes:
        - name: nfs-volume
          nfs:
           server: wdc-dr-isilon.company.com
           path: /wellness_poc
```

I am getting the below error in the logs : 
```
drupal 09:50:20.58 
drupal 09:50:20.58 Welcome to the Bitnami drupal container
drupal 09:50:20.59 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-drupal
drupal 09:50:20.59 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-drupal/issues
drupal 09:50:20.59 
drupal 09:50:20.59 INFO  ==> ** Starting Drupal setup **
drupal 09:50:20.63 INFO  ==> Configuring PHP options
drupal 09:50:20.63 INFO  ==> Setting PHP expose_php option
drupal 09:50:20.65 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
drupal 09:50:20.77 INFO  ==> Restoring persisted Drupal installation
drupal 09:50:20.87 INFO  ==> Trying to connect to the database server
grep: /opt/bitnami/drupal/sites/default/settings.php: No such file or directory
```
