### ISSUE TITLE
Custom SSL Certificate Permission Denied Error For Owners 1001 or nginx

### ISSUE THREAD

**Issue by ducarrozb** [bitnami/bitnami-docker-drupal#127]
I'm trying to use my own ssl certs but I'm struggeling around with the owner to set on my local host's directory and certificate files.
I tried with user 1001 and with user nginx, both users return a permission denied error message.
What am I missing?

docker-compose.yml
===============
```
drupal:
    image: docker.io/bitnami/drupal-nginx:9
...
    volumes:
      - 'drupal_data:/bitnami/drupal'
      - /volume/config/certs/UO/bitnami-drupal/my.own.crt:/opt/bitnami/nginx/conf/bitnami/certs/server.crt
      - /volume/config/certs/UO/bitnami-drupal/my.own.key:/opt/bitnami/nginx/conf/bitnami/certs/server.key
...
```

On the local host:
=============
```
/volume/config/certs/UO# ls -la bitnami-drupal/
total 20
drwxr-x--x 2 root root  4096 May 25 11:05 .
drwxr-x--x 5 root root  4096 May 25 11:05 ..
-r--r----- 1 root 1001 4180 May 25 11:05 my.own.crt
-rw-r----- 1 root 1001 1704 May 25 11:05 my.own.key
```

Error:
====
```
2021/05/25 09:18:03 [emerg] 164#164: cannot load certificate "/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') error:2006D002:BIO routines:BIO_new_file:system lib)
drupal_1   | nginx: [emerg] cannot load certificate "/opt/bitnami/nginx/conf/bitnami/certs/server.crt": BIO_new_file() failed (SSL: error:0200100D:system library:fopen:Permission denied:fopen('/opt/bitnami/nginx/conf/bitnami/certs/server.crt','r') error:2006D002:BIO routines:BIO_new_file:system lib)
```

**Comment by ducarrozb** [comment]
Hi, thank you for your response.
The container comes not up with my own certificates if I set them not readable for everyone. But when I remove the two lines and I use your standard image with the demo certificates, and then I log into the container, I see that the rights are set of root.root and readable to everyone which I would avoid for my own certs, due to security reasons:
```
I have no name!@fbdb98a3878f:/$ ls -la /opt/bitnami/nginx/conf/bitnami/certs/
drwxrwxr-x 2 root root 4096 May 25 13:59 .
drwxr-xr-x 1 root root 4096 May 26 07:40 ..
-rw-rw-r-- 1 root root  981 May 25 13:59 server.crt
-rw-rw-r-- 1 root root 1679 May 25 13:59 server.key
```
```
I have no name!@fbdb98a3878f:/$ whoami
whoami: cannot find name for user ID 1001
```
So my question is: would it be possible to you to change these rights directly in your standard image, setting them to something like root.1001 and chmod the rigts also inside the container to something like 440?
Or am I missing something?

**Comment by ducarrozb** [comment]
Just un update to complete:
I did the same now but with a docker-compose which uses local volumes. The problem is the same but with user rights root.1001. When I set my certificates readable to all, the container comes up, but I really would like to chmod 440 

docker-compose.yml
===============
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_PASSWORD=bitnami
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - /volume/usrdata/drupal/mariadb:/bitnami/mariadb
  drupal:
    image: docker.io/bitnami/drupal-nginx:9
    ports:
      - '80:8030'
      - '443:8443'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - DRUPAL_PASSWORD=bitnami
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_PASSWORD=bitnami
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
    volumes:
      - /volume/usrdata/drupal:/bitnami/drupal
      - /volume/config/certs/UObitnami-drupal/my.own.crt:/opt/bitnami/nginx/conf/bitnami/certs/server.crt
      - /volume/config/certs/UO/bitnami-drupal/my.own.key:/opt/bitnami/nginx/conf/bitnami/certs/server.key
    depends_on:
      - mariadb
```
This works:
========
```
ls -la /opt/bitnami/nginx/conf/bitnami/certs/
drwxrwxr-x 2 root root 4096 May 25 13:59 .
drwxr-xr-x 1 root root 4096 May 26 08:27 ..
-r--r--r-- 1 root 1001 4180 May 25 09:05 server.crt
-rw-r--r-- 1 root 1001 1704 May 25 09:05 server.key
```

This works not:
===========
```
ls -la /opt/bitnami/nginx/conf/bitnami/certs/
drwxrwxr-x 2 root root 4096 May 25 13:59 .
drwxr-xr-x 1 root root 4096 May 26 08:27 ..
-r--r----- 1 root 1001 4180 May 25 09:05 server.crt
-rw-r----- 1 root 1001 1704 May 25 09:05 server.key
```
