### ISSUE TITLE
Looking For Best Practice to Persist Drupal Files Using docker-compose.yml

### ISSUE THREAD

**Issue by ducarrozb** [bitnami/bitnami-docker-drupal#131]
Hi,

I try to use your image with a docker-compose.yml
By reading your doc https://hub.docker.com/r/bitnami/drupal I don't understand how your image manages the drupal files when trying to use a persistent local volume.

Is it meant that these files will be created automatically, the same way as your image does it with the database?
If so, how must I manage this?

As for now, what I tried, is to copy-past these files to my local volume by logging into the docker container as root and then to mount the local volume as you mentioned it:

```
 volumes:
      - /volume/usrdata/drupal/sites:bitnami/drupal
```
      
However, I run into several error messages by doing so.
Before I send all my error messages and what I tried, I just wonder if you can give me a hint what would be best practice to create persisting drupal files using a docker-compose.yml for your image - especially the user rights settings.

Thank you a lot!

**Comment by juan131** [comment]
Hi @ducarrozb 

Let me give you some context about how we manage persistence in this container.

Drupal files are, by default, under the `/opt/bitnami/drupal` directory. However, when the container is initialized for the 1st time (the 1st time you run the container) certain files/directories are moved to `/bitnami/drupal` and symlinks are created pointing from `/opt/bitnami/drupal` to `/bitnami/drupal`. This is done since we recommend mounting volumes at `/bitnami/drupal` to persist the application data, this way whatever modification you do to Drupal while running the app will survive to container restarts. 

What files/directories are moved to `/bitnami/drupal`? Basically those including Drupal's data. They're indicated in the `DRUPAL_DATA_TO_PERSIST ` env variable, see:

- https://github.com/bitnami/bitnami-docker-drupal/blob/master/9/debian-10/rootfs/opt/bitnami/scripts/drupal-env.sh#L75

This is also compatible with a common practice using containers to update the solution which is simply replacing your current image with a new version of the image. Since the data is persisted, you can replace the image and you won't lose anything. That's explained in this [section of the README.md](https://github.com/bitnami/bitnami-docker-drupal#upgrade-this-image)

**Comment by ducarrozb** [comment]
Holà Juan,

Thank your for this explanation. In this case, shouldn't the image create these files in my local `/volume/usrdata/drupal` folder when the container is initialized for the 1st time?

I used now for some tests

```
volumes:
      - /volume/usrdata/drupal:/bitnami/drupal
```

To be large and only for test issues, I setted the user-rights on /volume/usrdata/drupal to 777.

```
rm -r /volume/usrdata/drupal/*
rmdir /volume/usrdata/drupal
mkdir -p /volume/usrdata/drupal/mariadb/

chmod 777 /volume/usrdata/drupal/
chmod 775 /volume/usrdata/drupal/mariadb/
chown -R 1001.root /volume/usrdata/drupal/
```

However, the drupal files are not created into my local volume `/volume/usrdata/drupal/ `
But the mariadb is.

Result: the mariadb container is ok, but the drupal container exits.
What am I missing? - I always prune the volumes and download the latest image again - so everithing is reset to 0 for each new test.

**Comment by ducarrozb** [comment]
Hi again.
After several tests I found that it works like this:
```
 volumes:
      - /volume/usrdata/drupal:/bitnami
```
This creates me now the drupal files.

For everyone who reads this post, I add the docker-compose.yml which works actually:

Local Host Volume
==============
```
mkdir -p /volume/usrdata/drupal/mariadb/
chmod 775 /volume/usrdata/drupal/
chmod 775 /volume/usrdata/drupal/mariadb/
chown -R 1001.root /volume/usrdata/drupal/
```


docker-compose.yml
===============
```
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.5
    container_name: mariadb.3306 
    environment:
        - BITNAMI_DEBUG=true
        - MARIADB_CLIENT_FLAVOR=mariadb
        - MARIADB_CLIENT_DATABASE_HOST=mariadb
        - MARIADB_CLIENT_DATABASE_PORT_NUMBER=3306
        - MARIADB_CLIENT_DATABASE_ROOT_USER=root
        - MARIADB_CLIENT_DATABASE_ROOT_PASSWORD=mypass
        - MARIADB_CLIENT_CREATE_DATABASE_NAME=bitnami_drupal
        - MARIADB_CLIENT_CREATE_DATABASE_USER=mariadb.3306.drupal
        - MARIADB_CLIENT_CREATE_DATABASE_PASSWORD=mypass
        - MARIADB_CLIENT_CREATE_DATABASE_CHARACTER_SET=utf8
        - MARIADB_CLIENT_CREATE_DATABASE_PRIVILEGES=ALL
        - MARIADB_CLIENT_ENABLE_SSL_WRAPPER=no
        - MARIADB_CLIENT_ENABLE_SSL=no
        - MARIADB_ROOT_PASSWORD=mypass
        - MARIADB_USER=mariadb.3306.drupal
        - MARIADB_PASSWORD=mypass
        - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - /volume/usrdata/drupal/mariadb:/bitnami/mariadb
  drupal:
    image: docker.io/bitnami/drupal:latest
    container_name: drupal.8010
    ports:
            - '443:8443'
    environment:
        - BITNAMI_DEBUG=true
        - DRUPAL_PASSWORD=mypass
        - DRUPAL_DATABASE_USER=mariadb.3306.drupal
        - DRUPAL_DATABASE_PASSWORD=mypass
        - DRUPAL_DATABASE_NAME=bitnami_drupal
        - DRUPAL_DATABASE_HOST=mariadb
        - DRUPAL_DATABASE_PORT_NUMBER=3306
        - DRUPAL_PROFILE=standard
        - DRUPAL_SMTP_HOST=smtp.myhost.ch
        - DRUPAL_SMTP_PORT=587
        - DRUPAL_SMTP_USER=root@webserver.myhost.ch
        - DRUPAL_SMTP_PASSWORD=mypass
        - DRUPAL_SMTP_PROTOCOL=tls
        - PHP_EXPOSE_PHP=no
        - PHP_MEMORY_LIMIT=1024M
    volumes:
      - /volume/usrdata/drupal:/bitnami
      - /volume/config/certs/OU/bitnami-drupal/myhost.ch.crt:/opt/bitnami/apache/conf/bitnami/certs/server.crt
      - /volume/config/certs/OU/bitnami-drupal/myhost.ch.key:/opt/bitnami/apache/conf/bitnami/certs/server.key
    depends_on:
      - mariadb
```

Thank you again for your explanations, this helped me to fix the issue quickly.
